import React from "react";

export const metadata = {
    title: "Admin Layout",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <div className="text-2xl text-center text-blue-600">- Admin Layout -</div>
            {children}
        </>
    );
}
